project:
  type: book
  output-dir: docs

lang: pt-BR

book:
  title: "Estatística Multivariada"
  subtitle: "Notas de aula de um curso"
  author: "Carlos de Moura"
  date: "3/26/2026"
  chapters:
    - index.qmd
    - qmd/introducao.qmd
    - qmd/pca.qmd
    - qmd/referencias.qmd

bibliography: qmd/references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    include-in-header: mathjax-macros.js
  pdf:
    documentclass: scrreprt
    include-in-header: header.tex

